name: db-migration
version: 0.0.1
author: Aman Singh


default-extensions:
  - BangPatterns
  - DerivingStrategies
  - DeriveGeneric
  - DeriveAnyClass
  - OverloadedStrings
  - TypeFamilies
  - TypeApplications
  - BlockArguments
  - ScopedTypeVariables
  - DuplicateRecordFields
  - RecordWildCards
  - LambdaCase
  - NamedFieldPuns
  - DataKinds
  - MultiParamTypeClasses
  - FlexibleContexts
  - AllowAmbiguousTypes
  - GeneralizedNewtypeDeriving
  - ViewPatterns
  - GADTs

ghc-options:
  - -Wall
  - -O2

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - base
    - text
    - bytestring
    - unordered-containers
    - integer-gmp
    - beam-core
    - beam-postgres
    - beam-migrate
    - ghc-prim
    - postgresql-simple
    - vector
    - hashable
    - scientific
    - mtl
    - microlens
    - generic-deriving
    - free
    - extra
    - unliftio

executables:
  generate-dll:
    source-dirs: examples
    main: GenerateDDL
    dependencies:
      - aeson
      - base
      - bytestring
      - text
      - time
      - db-migration
      - beam-core
      - beam-migrate
      - beam-postgres
      - postgresql-simple
      - unordered-containers
      - mtl
      - extra
